var_group:
  percona_node_01_ip_address: "10.20.10.10"
  percona_node_02_ip_address: "10.20.10.11"
  percona_node_03_ip_address: "10.20.10.12"
  percona_node_01_hostname: "percdbtest01.fpn.local"
  percona_node_02_hostname: "percdbtest02.fpn.local"
  percona_node_03_hostname: "percdbtest03.fpn.local"
  percona_node_01_short_name: "percdbtest01"
  percona_node_02_short_name: "percdbtest02"
  percona_node_03_short_name: "percdbtest03"
  wsrep_cluster_name: "eqfpercdbtestclu01"
  