var_group:
  percona_node_01_ip_address: "10.20.10.10"
  percona_node_02_ip_address: "10.20.10.11"
  percona_node_03_ip_address: "10.20.10.12"
  percona_node_01_hostname: "PERCDBTEST01.lab.local"
  percona_node_02_hostname: "PERCDBTEST02.lab.local"
  percona_node_03_hostname: "PERCDBTEST03.lab.local"
  percona_node_01_short_name: "PERCDBTEST01"
  percona_node_02_short_name: "PERCDBTEST02"
  percona_node_03_short_name: "PERCDBTEST03"
  wsrep_cluster_name: "PERCDBTESTCLU01"
