## Fetch certificates from Node 01 to Ansible controller

- name: Create temporary certificate directory on controller
  ansible.builtin.file:
    path: /tmp/pxc-cluster-certs
    state: directory
    mode: "0700"
  delegate_to: localhost
  become: false
  run_once: true

- name: Fetch CA certificate from Node 01
  ansible.builtin.fetch:
    src: /etc/mysql/certs/ca.pem
    dest: /tmp/pxc-cluster-certs/ca.pem
    flat: true
  when: ansible_hostname in var_group['percona_node_01_short_name']

- name: Fetch server certificate from Node 01
  ansible.builtin.fetch:
    src: /etc/mysql/certs/server-cert.pem
    dest: /tmp/pxc-cluster-certs/server-cert.pem
    flat: true
  when: ansible_hostname in var_group['percona_node_01_short_name']

- name: Fetch server private key from Node 01
  ansible.builtin.fetch:
    src: /etc/mysql/certs/server-key.pem
    dest: /tmp/pxc-cluster-certs/server-key.pem
    flat: true
  when: ansible_hostname in var_group['percona_node_01_short_name']

  ## Create certificate directory on Nodes 02 and 03

- name: Create PXC certificate directory on other nodes
  ansible.builtin.file:
    path: /etc/mysql/certs
    state: directory
    owner: mysql
    group: mysql
    mode: "0750"
  when:
    - ansible_hostname in var_group['percona_node_02_short_name'] or
      ansible_hostname in var_group['percona_node_03_short_name']

## Distribute CA certificate

- name: Copy CA certificate to Nodes 02 and 03
  ansible.builtin.copy:
    src: /tmp/pxc-cluster-certs/ca.pem
    dest: /etc/mysql/certs/ca.pem
    owner: mysql
    group: mysql
    mode: "0644"
  when:
    - ansible_hostname in var_group['percona_node_02_short_name'] or
      ansible_hostname in var_group['percona_node_03_short_name']

## Distribute server certificate

- name: Copy server certificate to Nodes 02 and 03
  ansible.builtin.copy:
    src: /tmp/pxc-cluster-certs/server-cert.pem
    dest: /etc/mysql/certs/server-cert.pem
    owner: mysql
    group: mysql
    mode: "0644"
  when:
    - ansible_hostname in var_group['percona_node_02_short_name'] or
      ansible_hostname in var_group['percona_node_03_short_name']

## Distribute server private key

- name: Copy server private key to Nodes 02 and 03
  ansible.builtin.copy:
    src: /tmp/pxc-cluster-certs/server-key.pem
    dest: /etc/mysql/certs/server-key.pem
    owner: mysql
    group: mysql
    mode: "0600"
  when:
    - ansible_hostname in var_group['percona_node_02_short_name'] or
      ansible_hostname in var_group['percona_node_03_short_name']

## Restore SELinux contexts

- name: Restore SELinux context on certificate files
  ansible.builtin.command:
    cmd: restorecon -RF /etc/mysql/certs
  changed_when: false
  when:
    - ansible_hostname in var_group['percona_node_02_short_name'] or
      ansible_hostname in var_group['percona_node_03_short_name']
