---
  - name: SSH dir creation
    become: true
    become_user: fpnusr
    shell: mkdir -p /home/fpnusr/.ssh
    register: result
  - debug:
      msg: "{{ result.stdout }}"

  - name: Change file ownership for SSH keys
    ansible.builtin.file:
      path: "/home/fpnusr/.ssh"
      owner: fpnusr
      group: fpnusr
      mode: '700'
      recurse: yes
  
  - name: SSH dir creation
    become: true
    become_user: fpnusr
    shell: touch /home/fpnusr/.ssh/authorized_keys
    register: result
  - debug:
      msg: "{{ result.stdout }}"
  
  - name: Change file ownership for SSH keys
    ansible.builtin.file:
      path: "/home/fpnusr/.ssh/authorized_keys"
      owner: fpnusr
      group: fpnusr
      mode: '600'
 
  - name: Set up multiple authorized keys Mexsolutions fpnusr
    ansible.posix.authorized_key:
      user: fpnusr
      state: present
      key: '{{ item }}'
    with_file:
      - files/pub-keys/angel-laptop.pub
      - files/pub-keys/ee-laptop.pub
      - files/pub-keys/eecheverry.pub
      - files/pub-keys/gs-laptop.pub
      - files/pub-keys/gsandoval.pub
  
  - name: Add J2 template for sshd config file
    template:
      src: templates/sshd_config.j2
      dest: "/etc/ssh/sshd_config"
  
  - name: Change file ownership for sshd_config
    ansible.builtin.file:
      path: "/etc/ssh/sshd_config"
      owner: root
      group: root
      mode: '600'
  
  - name: Apply new SELinux file context to sshd_config
    shell: restorecon -v /etc/ssh/sshd_config
    register: result
  - debug:
      msg: "{{ result.stdout }}"

  - name: Allow the fpnusr user to run any commands as root with sudo -u root
    community.general.sudoers:
      name: fpnusr-do-as-root
      state: present
      user: fpnusr
      runas: root
      commands: ALL 
 
  - name: Apply new SELinux file context to sshd_config
    command: restorecon -v /etc/ssh/sshd_config
    register: result
  - debug:
      msg: "{{ result.stdout }}"

  - name: Restart service sshd for all servers.
    ansible.builtin.service:
      name: sshd
      state: restarted